version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration

output:
  show-stats: true

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/nickvanw/qbitorrent-tui


linters:
  enable:
    - bodyclose
    - govet
    - ineffassign
    - misspell
    - nakedret
    - unconvert
    - unparam
    - unused
    - whitespace
  
  disable:
    - errcheck
    - staticcheck
    - gochecknoglobals
    - godot
    - godox
    - nestif
    - testpackage
    - wsl

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
