version: '3'
services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=UTC
      - WEBUI_PORT=8080
    ports:
      - "8181:8080"
    volumes:
      - qbt-test-config:/config
      - qbt-test-downloads:/downloads
      - ./testdata/qBittorrent-working.conf:/config/qBittorrent/qBittorrent.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  qbt-test-config:
  qbt-test-downloads: